openapi: 3.0.0
info:
  title: MELI nesxtep
  description: |-
    This is the [BBF](https://sites.google.com/mercadolibre.com.co/cx-help/glosario#h.57dupv51nb1z) documentation for "my queries" [TOAD](https://furydocs.io/nesxtep/latest/guide/#/).  You can find out more about Swagger at [https://swagger.io](https://swagger.io).

    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    Some useful links:
    - [github repository](https://github.com/nesxtep/nesxtep)
    - [fury](https://nesxtep/nesxtep)
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Contact the team by slack
  url: https://meli.slack.com/archives/CS86TLPUK
servers:
  - url: https://www.nesxtep.com.co
    description: Prod
  - url: https://ayuda-stage.nesxtep.com.co
    description: Stage
  - url: https://ayuda-dev.nesxtep.com.co
    description: Dev
tags:
  - name: Case list filter
    description: Cases after filtered data
    externalDocs:
      description: Find out more
      url: https://furydocs.io/nesxtep/latest/guide/#/./route-features/cases